#ifndef LIBIRC2HTMLCODE_GLOBAL_H
#define LIBIRC2HTMLCODE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LIBIRC2HTMLCODE_LIBRARY)
#  define LIBIRC2HTMLCODESHARED_EXPORT Q_DECL_EXPORT
#else
#  define LIBIRC2HTMLCODESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // LIBIRC2HTMLCODE_GLOBAL_H
