#ifndef DEFINITIONS_H
#define DEFINITIONS_H

#define GRUMPY_VERSION_STRING "1.0.0"
#define CONFIGURATION_FILE "grumpy.ini"
#define CONFIGURATION_PATH "grumpyirc"
#define PRODUCTION_BUILD

#endif // DEFINITIONS_H

